MVC_AsistenciaDocente/Controllers/AsistenciaController.cs
using LibCryptoUTP;
using MVC_AsistenciaDocente.Models;
using MVC_AsistenciaDocente.ServiceAD;
using LICL_AsistenciaDocente_BL;
using LICL_AsistenciaDocente_EL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using System.Web.Security;
using System.Net;
using System.Web.Services.Protocols;
using System.Diagnostics;

using System.Net.Mail;
using System.Text;
using System.IO;

using System.Text.RegularExpressions;

namespace MVC_AsistenciaDocente.Controllers
{
    [HandleError(View = "_Error")]
    public class AsistenciaController : Controller
    {
      
        #region Objetos Globales
        Exception _ex;
        E_Parametros parametros;
        B_Docente obDocente;
        B_General oGeneral;
        
        B_Terminal obTerminal;

        //AsistenciaController ip = "10.60.8.12";      

        Stopwatch stopWatch;

        #endregion

        public string local_ps
        {
            get
            {
                if (parametros.validarIP == "1" & ConfigurationManager.AppSettings["TST"].ToString() == "0")
                {
                     var local_ps = obTerminal.validarIP_PS(ip, ref _ex);
                     Session["vUnidad"] = obTerminal.validarUnidad_PS(local_ps, ref _ex);
                     ViewBag.local_ps = local_ps;
                     return local_ps; //obTerminal.validarIP_PS( ip, ref _ex);
                }
                else
                {
                    if (Session["vlocal"] != null)
                    {
                        ViewBag.local_ps = Session["vlocal"].ToString();
                        return Session["vlocal"].ToString();
                    }
                    else
                    {
                        ViewBag.local_ps = "**";
                        return "**";
                    }
                }
            }
        }
 
        public string ip
        {
            /* original  */
            /*  get
            {
                //JBRAVO 15-02                
                return Request.ServerVariables["REMOTE_ADDR"].ToString().Replace(":", ".");
            }            
            */
            /* prueba   */
            get
            {
                return "10.20.30.4";
            }
           
        }

        public DateTime Fec_Actual
        {
            get
            {
                if (ConfigurationManager.AppSettings["TST"].ToString() == "0")
                    return DateTime.Now;
                else
                    return (DateTime)Session["vfecha"];
            }
        }

        #region ActionsResults
        [AllowAnonymous]
        public ActionResult Index()
        {
            return RedirectToAction("Login");
        }
        #endregion

        [AllowAnonymous]
        public ActionResult Login(string returnURL)
        {
            try
            {
                stopWatch = new Stopwatch();
                stopWatch.Start();
                //if (ConfigurationManager.AppSettings["TST"].ToString() == "0")
                //{

                //    if (parametros.tipo_acceso == "2") // PEOPLESOFT
                //    {
                //        //string ip2;
                //        //ip2='10.60.8.12';
                //        ViewBag.local_ps = obTerminal.validarIP_PS(ip, ref _ex);
                //    }                   
                //}
                //else
                //{
                //    ViewBag.local_ps = "**";
                //}

                if (parametros.validarIP == "1")
                {
                    if (parametros.tipo_acceso == "2")
                    {
                        // Process.Start("shutdown.exe", " -l");      
                        if (local_ps == "")
                        {
                            stopWatch.Stop();
                            var tasktime = stopWatch.ElapsedMilliseconds;

                            obTerminal.registraLog_ps("Anonimo", ip, "", "NAU", Request.Browser.Browser + " " + Request.Browser.Version + " ", tasktime, ref _ex);
                            ViewBag.loginmsg = "No puede acceder al sistema por encontrarse en una sede no válida para la marcación de asistencia.";
                        }
                    }                    
                }
                else
                {
                    ViewBag.local_ps = "**";
                }

                if (Request.IsAuthenticated)
                  return RedirectToAction("Horario");
                //Process.Start("shutdown.exe", " -l");
            }
            catch (Exception ex)
            {
                _ex = ex;
            }
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(Usuario oUsuario)        
        {
            stopWatch = new Stopwatch();
            stopWatch.Start();
            String msg = "";

            if (parametros.tipo_acceso == "2")
            {
                ViewBag.local_ps = obTerminal.validarIP_PS(ip, ref _ex);
            }
            
            if (parametros.validarIP == "1")
            {
                if (parametros.tipo_acceso == "2")
                {
                    if (local_ps.Trim() == "")
                    {
                        stopWatch.Stop();
                        var tasktime = stopWatch.ElapsedMilliseconds;

                        obTerminal.registraLog_ps("Anonimo", ip, "", "NOA", Request.Browser.Browser + " " + Request.Browser.Version + " ", tasktime, ref _ex);
                        ViewBag.loginmsg = "No puede acceder al sistema por encontrarse en una sede no válida para la marcación de asistencia.";
                        return View();
                    }
                }                
            }

            if (ConfigurationManager.AppSettings["TST"].ToString() == "1")
            {
                if (oUsuario.anio == 0)
                    Session["vfecha"] = DateTime.Now;
                else
                    Session["vfecha"] = new DateTime(oUsuario.anio, oUsuario.mes, oUsuario.dia, oUsuario.hora, oUsuario.min, 0);

                Session["vlocal"] = oUsuario.local;
            }

            oUsuario.usu = (oUsuario.usu == null) ? oUsuario.usu : oUsuario.usu.ToUpper();

            //if (parametros.tipo_acceso == "2")
            //{
            //    obTerminal.registraLog_ps(oUsuario.usu, ip, local_ps, "INT", Request.Browser.Browser + " " + Request.Browser.Version + " ", ref _ex);
            //}            

            try
            {
                if ((oUsuario.pwd == "" || oUsuario.usu == "") || (oUsuario.pwd == null || oUsuario.usu == null))
                {
                    msg = "Complete los campos obligatorios";
                    goto NoLogin;
                }
                
                //JBRAVO 
                if (parametros.validarAD == "1")
                {
                    int result = 0;
                    ServiceADSoapClient proxy = new ServiceADSoapClient();
                    EncriptaUTP cryp = new EncriptaUTP();
                    /*result = proxy.validaUsuarioAD(oUsuario.usu.Trim(), cryp.EncriptaAES128(oUsuario.pwd, "-+*%$({[]})$%*+-"), "ASIST");*/
                    result = 1;
                    if (result == 0)
                    {
                        msg = "Usuario y/o contraseña incorrecta";
                        goto NoLogin;
                    }
                }

                FormsAuthentication.SetAuthCookie(oUsuario.usu, true);
                Session["usuario"] = oUsuario.usu;
                Session["docente"] = oUsuario.usu;

                if (parametros.tipo_acceso == "2")
                {
                    stopWatch.Stop();
                    var tasktime = stopWatch.ElapsedMilliseconds;

                    obTerminal.registraLog_ps(oUsuario.usu, ip, local_ps, "ING", Request.Browser.Browser + " " + Request.Browser.Version, tasktime, ref _ex);
                }                

                return RedirectToAction("Horario");
            }
            catch (Exception ex)
            {
                string sError = ex.InnerException.ToString();
                sError = Regex.Replace(sError, @"[^0-9A-Za-z]", " ", RegexOptions.None);
                stopWatch.Stop();
                var tasktime = stopWatch.ElapsedMilliseconds;
                obTerminal.registraLog_ps(oUsuario.usu, ip, local_ps, "NOI", sError, tasktime, ref _ex);
               
                throw;
                //return RedirectToAction("Error", new { msg = ex.InnerException.Message });
            }

        NoLogin:

            if (parametros.tipo_acceso == "2")
            {
                stopWatch.Stop();
                var tasktime = stopWatch.ElapsedMilliseconds;

                obTerminal.registraLog_ps(oUsuario.usu, ip, local_ps, "NOI", Request.Browser.Browser + " " + Request.Browser.Version, tasktime, ref _ex);
            }
        
            ModelState.AddModelError("", msg);            
            return View();
        }

        public ActionResult LogOff()
        {
            try
            {
                //FormsAuthentication.SignOut();
                //return RedirectToAction("Login");
                Session.Clear();
                Session.Abandon();
                FormsAuthentication.SetAuthCookie(null, false);
                FormsAuthentication.SignOut();
                return RedirectToAction("Login");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", new { msg = ex.Message });
            }
        }

        public ActionResult Horario(string msg = "")
        {
            //if (!Request.IsAuthenticated)
            //    return RedirectToAction("Login");
            stopWatch = new Stopwatch();
            stopWatch.Start();
            string _msg = "";

MVC_AsistenciaDocente/Views/Shared/_Error.cshtml
@model System.Web.Mvc.HandleErrorInfo  
  
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
  
@*<h4>Error Details:</h4>  
<p>Controller Name: @Model.ControllerName</p>  
<p>Action Name: @Model.ActionName</p>  
<p>Exception: @Model.Exception</p>  *@

@*///////////////////////////////////////*@


<style>
.error-container {
	margin-top: 4em;
	margin-bottom: 4em;
	text-align: center;
        color: #333;
}

.error-container h1 {
	margin-bottom: .5em;
	
	font-size: 120px;
	line-height: 1em;
}

.error-container h2 {
	margin-bottom: .75em;
	font-size: 28px;
}

.error-container .error-details {
	margin-bottom: 1.5em;
	
	font-size: 16px;
}

.error-container .error-actions a {
	margin: 0 .5em;
} 
</style>

<div class="container">
    <div class="row">
        <div class="span12">
            <div class="error-container">
                <h1>Oops!</h1>                
                @*<h2>@Model.Exception</h2>*@	
                <h4>Error Details:</h4>  
                <p>Controller Name: @Model.ControllerName</p>  
                <p>Action Name: @Model.ActionName</p>  	
                @*<p style="color:red; text-align:justify">Exception: @Model.Exception.InnerException</p>*@	
                @*<div class="error-details">
                    Lo sentimos, ha ocurrido un error, no se ha encontrado la página solicitada!
                </div>*@

                <div class="alert alert-warning" role="alert" style='overflow: hidden; border-top-left-radius: 10px; border-top-right-radius: 10px; border-bottom-right-radius: 10px; border-bottom-left-radius: 10px; border: 2px solid rgb(255, 194, 55); box-shadow: rgba(0, 0, 0, 0.0980392) 0px 2px 4px; color: rgb(130, 98, 0); background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABsAAAAoCAYAAAAPOoFWAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAPZJREFUeNq81tsOgjAMANB2ov7/7ypaN7IlIwi9rGuT8QSc9EIDAsAznxvY4pXPKr05RUE5MEVB+TyWfCEl9LZApYopCmo9C4FKSMtYoI8Bwv79aQJU4l6hXXCZrQbokJEksxHo9KMOgc6w1atHXM8K9DVC7FQnJ0i8iK3QooGgbnyKgMDygBWyYFZoqx4qS27KqLZJjA1D0jK6QJcYEQEiWv9PGkTsbqxQ8oT+ZtZB6AkdsJnQDnMoHXHLGKOgDYuCWmYhEERCI5gaamW0bnHdA3k2ltlIN+2qKRyCND0bhqSYCyTB3CAOc4WusBEIpkeBuPgJMAAX8Hs1NfqHRgAAAABJRU5ErkJggg==) 0% 0% repeat-x scroll rgb(255, 234, 168);'>
                  <h4 class="alert-heading"> Lo sentimos, ha ocurrido un error!</h4>                  
                  <p>Exception: @Model.Exception.InnerException</p>
                  <hr>
                  <p class="mb-0">Sistema de Marcación Docente</p>
                </div>
                <div class="error-actions">
                    <a href="javascript:;" onclick="history.back();" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-home"></span> Regresar </a>
                    <a href="http://mesadeayuda.utp.edu.pe" target="_blank" class="btn btn-default btn-lg"><span class="glyphicon glyphicon-envelope"></span> Contacte con el soporte </a>
                </div>
            </div>
        </div>
    </div>
</div>

MVC_AsistenciaDocente/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es-pe">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="x-ua-compatible" content="IE=9">

    @{
        var cIcon = (Session["vUnidad"].ToString() == "UNIDT") ? "favicon_IDT.ico" : "favicon_UTP.ico";
    }
    
    <title>..::Sistema de Marcación Docente::..</title>

    <link href="~/Images/@cIcon" rel="icon" type="image/x-icon" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/css/bootstrap-toggle.min.css" rel="stylesheet" />
    <link href="~/css/bootstrap-dialog.min.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    
</head>
<body>
    <header>
        @Html.Partial("_PartialHeader")
    </header>
    @if (Request.IsAuthenticated)
    {
        @Html.Partial("_PartialDocente")
    }
    <div class="container">
        @RenderBody()
    </div>

    @*<div id="notifications" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Configuracion de alertas</h4>
                </div>
                @using (Html.BeginForm())
                {
                    <div class="modal-body">
                        <p>Configure sus alertas</p>

                        <label for="txtTelefono">Telefono</label>
                        <div class="input-group">

                            <span class="input-group-addon" id="basic-addon1">
                                <span class="glyphicon glyphicon-phone"></span>
                            </span>


                            <input type="tel" id="txtTelefono" class="form-control" />
                        </div>

                        <label for="txtCorreo">Correo electronico</label>
                        <div class="input-group">

                            <span class="input-group-addon" id="basic-addon2">
                                <span class="glyphicon glyphicon-envelope"></span>
                            </span>

                            <input type="email" id="txtCorreo" class="form-control" />
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" data-dismiss="modal">Aceptar</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    </div>
                }
            </div>*@
  @*  </div>
    </div>*@


    <!--==============================================================
                            SCRIPTS
        ==============================================================-->
    
    <script src="~/js/jquery-1.11.3.js"></script>
    <script src="~/js/bootstrap.js"></script>
    <script src="~/js/bootstrap-toggle.min.js"></script>
    <script src="~/js/bootstrap-dialog.min.js"></script>
    
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 10]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    @Html.Partial("_PartialFooter")


    <script>
        //$("#msg").modal('show');

        $('#pwd').bind('keyup', function (e) {
            var key = e.keyCode || e.which;
            if (key === 13) {
                this.submit();
            };
        });

        //$('#btnlog').click(function () {
          //  $('#btnlog').attr('disabled', true);
        //});

        $("#btnlog").closest('form').on('submit', function (e) {
            e.preventDefault();
            $('#btnlog').attr('disabled', true);
            this.submit(); // ahora hace el submit de tu formulario.
        });


        $("#btnAlu").closest('form').on('submit', function (e) {
            e.preventDefault();
            $('#btnAlu').text('Procesando')
            $('#btnAlu').attr('disabled', true);
            this.submit(); // ahora hace el submit de tu formulario.
        });

    </script>

</body>
</html>

MVC_AsistenciaDocente/Views/Shared/_PartialDocente.cshtml
@*<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">*@
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

@*<h4>Please wait for <span id="count"></span> seconds to view session timeout popup.</h4>*@

 <!--Start Show Session Expire Warning Popup here -->
    <div class="modal fade" id="session-expire-warning-modal" aria-hidden="true" data-keyboard="false" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">                  
                    <h4 style="color:green" class="modal-title">Tu sesión está a punto de expirar</h4>
                </div>
                <div class="modal-body">
                   <label style="color:red"><span class="glyphicon glyphicon-time"></span>  Sesión expira en:  <span id="seconds-timer"></span>s </label><p />

                    Si deseas mantener tu sesión por favor presiona continuar
                </div>
                <div class="modal-footer">
                    <button id="btnOk" type="button" class="btn btn-success" >Continuar <span class="glyphicon glyphicon-chevron-right"></span></button>
                    @*<button id="btnSessionExpiredCancelled" type="button" class="btn btn-default" data-dismiss="modal" style="padding: 6px 12px; margin-bottom: 0; font-size: 14px; font-weight: normal; border: 1px solid transparent; border-radius: 4px; background-color: #428bca; color: #FFF;">Cancel</button>*@
                    @*<button id="btnLogoutNow" type="button" class="btn btn-default" style="padding: 6px 12px; margin-bottom: 0; font-size: 14px; font-weight: normal; border: 1px solid transparent; border-radius: 4px;  background-color: #428bca; color: #FFF;">Logout now</button>*@
                </div>
            </div>
        </div>
    </div>
    <!--End Show Session Expire Warning Popup here -->
    <!--Start Show Session Expire Popup here -->
    <div class="modal fade" id="session-expired-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Sesión expirada</h4>
                </div>
                <div class="modal-body">
                    Su sesión ha expirado.
                </div>
                <div class="modal-footer">
                    <button id="btnExpiredOk" onclick="sessionExpiredRedirect()" type="button" class="btn btn-primary" data-dismiss="modal" style="padding: 6px 12px; margin-bottom: 0; font-size: 14px; font-weight: normal; border: 1px solid transparent; border-radius: 4px; background-color: #428bca; color: #FFF;">Ok</button>
                </div>
            </div>
        </div>
    </div>
	<script src="~/js/sessionTimeout.js"></script>
	 <!-- This will init session -->
	<script>
	 initSessionMonitor();
	</script>
	 <!-- This script is only for show cound down timer on HTML Page -->
@*<script type="text/javascript">

window.onload = function(){

(function(){
  var counter = 20;

  setInterval(function() {
    counter--;
    if (counter >= 0) {
      span = document.getElementById("count");
      span.innerHTML = counter;
    }    
    if (counter === 0) {      
        clearInterval(counter);
    }

  }, 1000);

})();

}
</script>*@

@{
    
    if (Session["vUnidad"].ToString() == "UNUTP") 
    { 
        var vmargin  = (Convert.ToBoolean(Session["notifyDelegado"])) ? "100px" : "0px";
        var vpadding = (Convert.ToBoolean(Session["notifyDelegado"])) ? "100px" : "0px";

        if (Convert.ToBoolean(Session["DiferenciaIPs"]))
        {
            <div id="notifyDiferenciaIPs" style="bottom: 5px; right: 5px; position: fixed; width: 310px; height: auto; margin: @vmargin; padding: @vpadding; list-style-type: none; z-index: 10000000; display: none;">
                <div class="notibar" id="notibar">
                    <div class='wrap_noti alerta notify' 
                        style='overflow: hidden; border-top-left-radius: 10px; border-top-right-radius: 10px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; border: 5px solid white!important; box-shadow: rgba(0, 0, 0, 0.0980392) 0px 2px 4px; color: white; width: 310px; background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABsAAAAoCAYAAAAPOoFWAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAPZJREFUeNq81tsOgjAMANB2ov7/7ypaN7IlIwi9rGuT8QSc9EIDAsAznxvY4pXPKr05RUE5MEVB+TyWfCEl9LZApYopCmo9C4FKSMtYoI8Bwv79aQJU4l6hXXCZrQbokJEksxHo9KMOgc6w1atHXM8K9DVC7FQnJ0i8iK3QooGgbnyKgMDygBWyYFZoqx4qS27KqLZJjA1D0jK6QJcYEQEiWv9PGkTsbqxQ8oT+ZtZB6AkdsJnQDnMoHXHLGKOgDYuCWmYhEERCI5gaamW0bnHdA3k2ltlIN+2qKRyCND0bhqSYCyTB3CAOc4WusBEIpkeBuPgJMAAX8Hs1NfqHRgAAAABJRU5ErkJggg==) 0% 0% repeat-x scroll #e74a3b!important;'>
                        <div align="right"><a href='#' class='icon-remove' onclick="$('#notifyDiferenciaIPs').slideUp();" style="color:white!important">x</a>&nbsp;&nbsp;&nbsp;&nbsp;</div>
                        <div style="font: normal 13px Tahoma; text-align:justify; padding: 5px 5px 5px 5px;">
                            <p><b>- Alerta! -</b></p>
                            Estimado(a) Docente <b>@ViewBag.docente</b><br />
                            la Marcación de su asistencia y la toma de la asistencia de Alumnos se realizaron en diferentes instalaciones, por lo que               
                            se procederá a guardar el registro en el LOG, sin que este afecte su marcación<p />
                            <div style='font: normal 11px Tahoma; color: white; border-top: solid 2px white!important; padding-top: 8px;'>Sistema de Marcación Docente</div>
                        </div>
                    </div>
                </div>
            </div>
    
        }    
    }                   
}

MVC_AsistenciaDocente/Views/Shared/_PartialFooter.cshtml
@*<div class="footer">
        <div class="container">
            Mesa de Ayuda : Teléfono 01 315-9606 | <a href="http://mesadeayuda.utp.edu.pe" target="_blank">mesadeayuda.utp.edu.pe</a><br />
            Copyright © 2016, Universidad Tecnológica del Perú | <a href="Docs/Aviso_Privacidad.pdf" target="_blank">Aviso de privacidad</a> | <a href="Docs/Terminos_Uso.pdf" target="_blank">Términos y condiciones de uso</a>
        </div>
    </div>*@



@*<input type="hidden">@ip</10>*@

<script>
    console.log("Type = @Request.Browser.Type");
    console.log("Name = @Request.Browser.Browser");
    console.log("Version = @Request.Browser.Version");
    @*console.log("Major Version = @Request.Browser.MajorVersion");
    console.log("Minor Version = @Request.Browser.MinorVersion");*@
    console.log("Platform = @Request.Browser.Platform");
    @*
    console.log("Is Beta = @Request.Browser.Beta");
    console.log("Is Crawler = @Request.Browser.Crawler");
    console.log("Is AOL = @Request.Browser.AOL");
    console.log("Is Win16 = @Request.Browser.Win16");
    console.log("Is Win32 = @Request.Browser.Win32");
    console.log("Supports Frames = @Request.Browser.Frames");
    console.log("Supports Tables = @Request.Browser.Tables");
    console.log("Supports Cookies = @Request.Browser.Cookies");
    console.log("Supports VBScript = @Request.Browser.VBScript");
    *@
    console.log("Local AS = @ViewBag.local_as");
    console.log("Local PS = @ViewBag.local_ps");
    @*console.log("Session ID = @Session.SessionID");*@
    console.log("IP ADDRESS = @Request.ServerVariables["REMOTE_ADDR"]");
</script>

MVC_AsistenciaDocente/Views/Shared/_PartialHeader.cshtml
<div class="header">
    <div class="navbar" style="background-color: white">
        <div style="text-align: center; display: block">

            @{
                var cLogo = (Session["vUnidad"].ToString() == "UNUTP") ? "logo_UTP.png" : (Session["vUnidad"].ToString() == "UNIDT") ? "logo_IDT.png" : "logo_EPG.png";                       
            }

            <img src="~/Images/@cLogo" style="height: 80px;" />
        </div>
        @if (Request.IsAuthenticated)
        {
            <div style="display: block; text-align: right">
                @*@Html.ActionLink("Salir", "LogOff", "Asistencia")*@

                <a href="@Url.Action("Logoff", "Asistencia")">
                    <span class="glyphicon glyphicon-off"></span> Cerrar Sesión
                </a>
            </div>
        }
    </div>
</div>

@*
    @if (Request.IsAuthenticated)
    {
        <nav class="navbar navbar-default">
            <div class="container">
                <div class="navbar-header">
                    <button aria-controls="navbar" aria-expanded="false" class="navbar-toggle collapsed" data-target="#navbar" data-toggle="collapse" type="button">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <span class="navbar-brand">Sistema de Control de asistencia
                    </span>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">

                        <li>
                            <a href="@Url.Action("Logoff", "Asistencia")" >
                                <span class="glyphicon glyphicon-off"></span>Cerrar Sesión
                            </a>
                        </li>
                    </ul>
                </div>

            </div>
        </nav>
    }   *@